  <section class="hero">
    <div class="hero__shadow js__bg"></div>
    <div class="hero__content d-flex flex-column justify-content-center align-items-center">
      <div class="w-85 text-center logo-holder">
        <!-- <img src="https://img.<?= DOMAIN_NAME ?>/ft_assets/img/Logo_960x270_white_sub.png" class="img-fluid"> -->
        <h1 class="hero__title main">JILNESTA</h1>
        <span>Challenge to limit</span>
      </div>
    </div>
  </section>