<noscript style="position: fixed; top: 0; left: 0; right: 0; bottom: 0; z-index: 1000000; background: #fff; text-align: center; padding-top: 5%;">
	<div style="font-size: 30px">
		<img src="/assets/images/image_nojavascript.png" style="display: block;max-width: 100%;"><br>
   		<b style=" color: #ccc; font-size: 30px;">Please enable javascript to continue.</b><br> <b style="font-weight: 500;font-size: 23px;">Thanks you!</b>
	</div>
</noscript>