<style type="text/css">
    .card{
        display: flex;
        width: 100%;
        height: 95vh;
        align-items: center;
        justify-content: center;
    }
    .card-body h1{
        text-align: center;
        font-weight: bold;
        font-size: 13em;
        color: #494E52;
        margin: 0;
        line-height: 1;
    }
    .blue-text{
        color: #409bee;
    }
    .card-body h1 span.or{
        color: #494E52;
    }
    .card-body{
        text-align: center;
    }
    .card-body h2 {
        text-align: center;
        color: #999;
        font-size: 50px;
        margin: 0;
    }
    .card-body p {
        text-align: center;
    }
    .card-body a{
        font-weight: bold;
        font-size: 30px;
    }
    .card-body h1 span { display:inline-block; }
    @media (max-width: 767px){
        .card-body h1{
            text-align: center;
            font-weight: bold;
            font-size: 8em;
            color: #494E52;
        }
        .card-body h2{
            font-size: 1.3em;
        }
        .card-body a{
            font-size: 1.6em;
        }
    }
    @keyframes float {
      0%,100%{ transform:none; }
      33%{ transform:translateY(-1px) rotate(-2deg); }
      66%{ transform:translateY(1px) rotate(2deg); }
    }
    /* .card-body h1:hover span { animation:bounce .8s; } */
    @keyframes bounce {
      0%,100%{ transform:translate(0); }
      25%{ transform:rotateX(20deg) translateY(2px) rotate(-3deg); }
      50%{ transform:translateY(-20px) rotate(3deg) scale(1.1);  }
    }
    /* .card-body h1 span:nth-child(2){ animation-delay:.05s; }
    .card-body h1 span:nth-child(3){ animation-delay:.15s; }
    .card-body h1 span:nth-child(4){ animation-delay:.25s; } */
</style>
<div class="card-body card-padding">
    <?php $this->layout('layout/error');?>
    <h1><span>4</span><span class="or">0</span><span>4</span></h1>
    <?php 
    echo '<img src="/'. APPLICATION_SKIN_NAME .'/images/404-images.jpg" style="width:80%" />';
    ?>
    <h2><?php echo $this->translate('Page does not exist') ?></h2>
    <a href="<?php echo $this->zfUrl('home')?>" class="blue-text"><?php echo $this->translate('Back to top page') ?></a>
</div>